version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_rest_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/Servidores
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 615712

  db:
    image: postgres:latest
    container_name: postgres_db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 615712
      POSTGRES_DB: Servidores
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
