version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_rest_container
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_PUBLIC_URL}         
      POSTGRES_USER: ${POSTGRES_USER}       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
