version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_rest_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER={DATABASE_USER}
      - DATABASE_PASSWORD={DATABASE_PASSWORD}

volumes:
  pg_data:
